### ISSUE TITLE
Not working with boot2docker on Mac OS X

### ISSUE THREAD

**Issue by trondgzi** [ibm-messaging/mqlight-docker#1]
I'm trying to run this command with boot2docker v1.5.0:

`docker run --env LICENSE=accept --volume /usr/local/var/docker/mqlight:/var/mqlight --publish 5672:5672 --publish 9180:9180 ibmimages/mqlight:early-access`

And this is my output:

```
+ mqlight-config -v

Licensed Materials - Property of IBM 

 5725-P60 

 (C) Copyright IBM Corporation 1994, 2015 

US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.


Name:        IBM MQ Light
Version:     1.0.0.1
Level:       pkoa-L150205.1
BuildType:   IKAP - (Production)
O/S:         Linux 3.18.5-tinycore64
InstPath:    /opt/mqlight/runtime
DataPath:    /var/mqlight/mqm
LicenseType: Early access

+ mqlight-config --accept-license

Licensed Materials - Property of IBM 

 5725-P60 

 (C) Copyright IBM Corporation 1994, 2015 

US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.


License agreement accepted.
AMQ7191: There are 6 days left in the beta test period for this copy of WebSphere MQ.
AMQ8001: WebSphere MQ queue manager created.
AMQ7263: Directory '/var/mqlight/mqm/qmgrs/DEFAULT' created.
The queue manager is associated with installation 'MQNI08000002'.
AMQ7017: Log not available.
AMQCF1018E: Unable to create the queue manager. Error code: 23.
```

**Comment by trondgzi** [comment]
Turns out that under boot2docker you can only use directories under /User when mounting a volume.

`docker run --env LICENSE=accept --volume $HOME/docker/mqlight:/var/mqlight --publish 5672:5672 --publish 9180:9180 ibmimages/mqlight:early-access`

Produces this output:

```
+ mqlight-config -v

Licensed Materials - Property of IBM 

 5725-P60 

 (C) Copyright IBM Corporation 1994, 2015 

US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.


Name:        IBM MQ Light
Version:     1.0.0.1
Level:       pkoa-L150205.1
BuildType:   IKAP - (Production)
O/S:         Linux 3.18.5-tinycore64
InstPath:    /opt/mqlight/runtime
DataPath:    /var/mqlight/mqm
LicenseType: Early access

+ mqlight-config --accept-license

Licensed Materials - Property of IBM 

 5725-P60 

 (C) Copyright IBM Corporation 1994, 2015 

US Government Users Restricted Rights - Use, duplication or disclosure
restricted by GSA ADP Schedule Contract with IBM Corp.


License agreement accepted.
AMQ7063: An INI file is missing.
AMQCF1018E: Unable to create the queue manager. Error code: 71.
```

If I try to run without mounting a volume it works: `docker run --env LICENSE=accept --publish 5672:5672 --publish 9180:9180 ibmimages/mqlight:early-access`

**Comment by IBMRob** [comment]
I think this is the same underlying problem as [boot2docker issue #587 ](https://github.com/boot2docker/boot2docker/issues/587#issuecomment-99145322) which means that the file permissions are not translated properly when you use the /Users folder. If you tell docker to use the boot2docker hard drive then it should work as a workaround i.e. something like /mnt/sda1/mqlight/

**Comment by dnwe** [comment]
@RobQuads so I don't think that the mqlight image should be effected by that particular issue, as with the latest mqlight image we run as a user with 1000:50, so the file vbox mount permissions correctly match the running user.

I wasn't able to reproduce the issue reported by @trondgzi ─ when I tried to map a drive outside of $HOME, it just silently ignored it and /var/mqlight was with the aufs layer.

However, I'm still seeing issues in boot2docker + osx when restarting the container

**Comment by trondgzi** [comment]
@dnwe I just upgraded to docker/boot2docker 1.6.1 (installed with brew) and I still have issues.

Trying to map outside of $HOME results in:

```
...
Starting MQ Light.........
AMQ7191: There are 231 days left in the beta test period for this copy of WebSphere MQ.
AMQ7017: Log not available.
```

Mapping inside $HOME:

```
...
Starting MQ Light.........
AMQ7191: There are 231 days left in the beta test period for this copy of WebSphere MQ.
AMQ6119: An internal WebSphere MQ error has occurred ()
```

The only way I can make it start is to not use a mapping

**Comment by davidjmccann** [comment]
Using the latest image it should now be possible to use file systems outside of $HOME. However, it is still not possible to map to $HOME because of [a VirtualBox bug](https://www.virtualbox.org/ticket/819). An error message will be returned if an attempt is made to map to a file system affected by this bug.

Note that under boot2docker mapped locations outside of $HOME will, by default, only be available from within the boot2docker VM.
